# Generated by Django 2.2.5 on 2019-10-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='Apply_To',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='Attachment',
            field=models.FileField(default='', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='Cc_To',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='Contact_Details',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='From_Session',
            field=models.CharField(choices=[('session1', 'session2')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='To_Session',
            field=models.CharField(choices=[('session1', 'session2')], default='', max_length=10),
        ),
    ]
