# Generated by Django 2.2.5 on 2019-10-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20191009_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='From_Session',
            field=models.CharField(choices=[('session1', 'session1'), ('session2', 'session2')], default='session1', max_length=10),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='To_Session',
            field=models.CharField(choices=[('session1', 'session1'), ('session2', 'seassion2')], default='session2', max_length=10),
        ),
    ]
