# Generated by Django 2.2.5 on 2019-10-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20191009_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='From_Session',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='To_Session',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='Fromsession',
            field=models.CharField(choices=[('Session1', 'Session1'), ('Session2', 'Session2')], default='Session1', max_length=50),
        ),
    ]
