# Generated by Django 2.2.5 on 2019-10-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20191009_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='Tosession',
            field=models.CharField(choices=[('Session1', 'Session1'), ('Session2', 'Session2')], default='Session1', max_length=50),
        ),
    ]
