# Generated by Django 2.2.5 on 2019-10-09 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_leaverequest_tosession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='Apply_To',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='Cc_To',
        ),
    ]
