# Generated by Django 2.2.5 on 2019-10-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20191009_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='Contact_Details',
            new_name='Contact',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='ApplyTo',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='CcTo',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
