# Generated by Django 2.2.5 on 2019-10-13 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20191013_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='Days',
        ),
    ]
